//! `Interp::new` builtin-class registration — the static decl table
//! for SPL/Exception/reflection classes the engine predeclares.

use super::*;

impl<'a> Interp<'a> {
    /// Builtin exception classes + interfaces needed by try/catch.
    pub(in crate::interp) fn register_builtin_classes(&mut self) {
        fn throwable_class(name: &str, parent: Option<&str>, props: &[&str]) -> ClassDecl {
            ClassDecl {
                name: name.into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: parent.map(|s| s.to_string()),
                implements: vec!["Throwable".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    method("__construct", &["message", "code", "previous"]),
                    method("getMessage", &[]),
                    method("getCode", &[]),
                    method("getFile", &[]),
                    method("getLine", &[]),
                    method("getTrace", &[]),
                    method("getTraceAsString", &[]),
                    method("getPrevious", &[]),
                    method("__toString", &[]),
                ],
                props: props
                    .iter()
                    .map(|p| PropDecl {
                        name: p.to_string(),
                        default: None,
                        is_static: false,
                        visibility: Visibility::Protected,
                        readonly: false,
                        ty: None,
                        is_abstract: false,
                        is_final: false,
                        set_vis: None,
                        decl_in: None,
                        hooks: None,
                        attrs: vec![],
                        line: 0,
                    })
                    .collect(),
                consts: vec![],
                file: String::new(),
                line: 0,
            }
        }
        fn method(name: &str, _params: &[&str]) -> Rc<MethodDecl> {
            Rc::new(MethodDecl {
                decl: FunctionDecl {
                    ret: None,
                    name: name.into(),
                    params: vec![],
                    body: vec![],
                    attrs: vec![],
                    by_ref: false,
                    line: 0,
                    end_line: 0,
                    file: String::new(),
                    ns: String::new(),
                    decl_in: None,
                },
                is_static: false,
                is_abstract: false,
                is_final: false,
                visibility: Visibility::Public,
                trait_alias_of: None,
            })
        }
        let mut reg = |d: ClassDecl, is_iface: bool| {
            let c = Rc::new(PhpClass {
                decl: Rc::new(d),
                statics: RefCell::new(HashMap::new()),
                statics_init: RefCell::new(true),
            });
            if is_iface {
                self.builtin_ifaces.insert(c.decl.name.to_lowercase());
                self.interfaces
                    .insert(c.name().to_lowercase(), c.decl.clone());
            } else {
                self.classes.insert(c.name().to_lowercase(), c);
            }
        };
        // Throwable interface + Error/Exception hierarchy.
        let iface = |name: &str, parents: &[&str], methods: &[&str]| ClassDecl {
            name: name.into(),
            kind: ClassKind::Interface,
            is_abstract: false,
            is_final: false,
            readonly: false,
            parent: None,
            implements: parents.iter().map(|s| s.to_string()).collect(),
            attrs: vec![],
            traits: vec![],
            adaptations: vec![],
            methods: methods
                .iter()
                .map(|m| {
                    Rc::new(MethodDecl {
                        decl: FunctionDecl {
                            ret: None,
                            name: m.to_string(),
                            params: vec![],
                            body: vec![],
                            attrs: vec![],
                            by_ref: false,
                            line: 0,
                            end_line: 0,
                            file: String::new(),
                            ns: String::new(),
                            decl_in: None,
                        },
                        is_static: false,
                        is_abstract: true,
                        is_final: false,
                        visibility: Visibility::Public,
                        trait_alias_of: None,
                    })
                })
                .collect(),
            props: vec![],
            consts: vec![],
            file: String::new(),
            line: 0,
        };
        reg(iface("Throwable", &[], &[]), true);
        reg(iface("Stringable", &[], &["__toString"]), true);
        reg(iface("Traversable", &[], &[]), true);
        reg(
            iface(
                "Iterator",
                &["Traversable"],
                &["current", "key", "next", "rewind", "valid"],
            ),
            true,
        );
        reg(
            iface("IteratorAggregate", &["Traversable"], &["getIterator"]),
            true,
        );
        reg(iface("Countable", &[], &["count"]), true);
        reg(iface("Reflector", &[], &[]), true);
        // Serializable's unserialize takes `string $data` — the iface()
        // helper emits param-less methods, so patch the decl (the
        // interface-sig check compares against it).
        let mut sd = iface("Serializable", &[], &["serialize", "unserialize"]);
        for m in sd.methods.iter_mut() {
            if m.decl.name == "unserialize" {
                let mut m2 = (**m).clone();
                m2.decl.params = vec![Param {
                    name: "data".into(),
                    default: None,
                    by_ref: false,
                    variadic: false,
                    ty: Some(vec!["string".into()]),
                    promoted: false,
                    vis: None,
                    readonly: false,
                    is_final: false,
                    set_vis: None,
                    hooks: None,
                }];
                *m = Rc::new(m2);
            }
        }
        reg(sd, true);
        // SPL Observer pair — param-typed per the real SPL stubs so
        // interface-sig checks accept real-world impls (ns_054/056).
        let spl_param = |n: &str, t: &str| Param {
            name: n.into(),
            default: None,
            by_ref: false,
            variadic: false,
            ty: Some(vec![t.into()]),
            promoted: false,
            vis: None,
            readonly: false,
            is_final: false,
            set_vis: None,
            hooks: None,
        };
        let mut so = iface("SplObserver", &[], &["update"]);
        so.methods[0] = {
            let mut m = (*so.methods[0]).clone();
            m.decl.params = vec![spl_param("subject", "SplSubject")];
            Rc::new(m)
        };
        reg(so, true);
        let mut ss = iface("SplSubject", &[], &["attach", "detach", "notify"]);
        for (i, pn) in ["observer", "observer", ""].iter().enumerate() {
            let mut m = (*ss.methods[i]).clone();
            m.decl.params = if pn.is_empty() {
                vec![]
            } else {
                vec![spl_param(pn, "SplObserver")]
            };
            ss.methods[i] = Rc::new(m);
        }
        reg(ss, true);
        reg(iface("SeekableIterator", &["Iterator"], &["seek"]), true);
        reg(
            iface(
                "RecursiveIterator",
                &["Iterator"],
                &["hasChildren", "getChildren"],
            ),
            true,
        );
        // ArrayIterator — SPL iterator over an array; methods are
        // native-dispatched (array_iter_method) on the ArrayIter
        // internal. Named-arg params carry the Zend stub names.
        let stub_method = |name: &str, params: &[&str]| {
            Rc::new(MethodDecl {
                decl: FunctionDecl {
                    ret: None,
                    name: name.into(),
                    params: params
                        .iter()
                        .map(|n| Param {
                            name: n.to_string(),
                            default: None,
                            by_ref: false,
                            variadic: false,
                            ty: None,
                            promoted: false,
                            vis: None,
                            readonly: false,
                            is_final: false,
                            set_vis: None,
                            hooks: None,
                        })
                        .collect(),
                    body: vec![],
                    attrs: vec![],
                    by_ref: false,
                    line: 0,
                    end_line: 0,
                    file: String::new(),
                    ns: String::new(),
                    decl_in: None,
                },
                is_static: false,
                is_abstract: false,
                is_final: false,
                visibility: Visibility::Public,
                trait_alias_of: None,
            })
        };
        // stub where `req` params are required and `opt` have null defaults
        let stub_method_mix = |name: &str, req: &[&str], opt: &[&str]| {
            let m = stub_method(
                name,
                &req.iter().chain(opt.iter()).copied().collect::<Vec<_>>(),
            );
            let mut decl = m.decl.clone();
            for p in decl.params.iter_mut().skip(req.len()) {
                p.default = Some(Expr::Null);
            }
            Rc::new(MethodDecl {
                decl,
                is_static: m.is_static,
                is_abstract: m.is_abstract,
                is_final: m.is_final,
                visibility: m.visibility,
                trait_alias_of: None,
            })
        };
        // stub with typed params per the Zend SPL arginfo — userland
        // overrides declaring the same types stay signature-compatible.
        let stub_method_typed = |name: &str, params: &[(&str, &str)]| {
            let names: Vec<&str> = params.iter().map(|(n, _)| *n).collect();
            let mut m = (*stub_method(name, &names)).clone();
            for (p, (_, t)) in m.decl.params.iter_mut().zip(params.iter()) {
                p.ty = Some(vec![t.to_string()]);
            }
            Rc::new(m)
        };

        reg(
            ClassDecl {
                name: "ArrayIterator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![
                    "SeekableIterator".into(),
                    "ArrayAccess".into(),
                    "Countable".into(),
                    "Serializable".into(),
                ],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                // Decl order mirrors zend's arginfo/function_table order
                // — get_class_methods() lists it verbatim.
                methods: vec![
                    stub_method("__construct", &["array", "flags"]),
                    stub_method("offsetExists", &["key"]),
                    stub_method("offsetGet", &["key"]),
                    stub_method("offsetSet", &["key", "value"]),
                    stub_method("offsetUnset", &["key"]),
                    stub_method("append", &["value"]),
                    stub_method("getArrayCopy", &[]),
                    stub_method("count", &[]),
                    stub_method("getFlags", &[]),
                    stub_method("setFlags", &["flags"]),
                    stub_method("asort", &["flags"]),
                    stub_method("ksort", &["flags"]),
                    stub_method("uasort", &["callback"]),
                    stub_method("uksort", &["callback"]),
                    stub_method("natsort", &[]),
                    stub_method("natcasesort", &[]),
                    stub_method_typed("unserialize", &[("data", "string")]),
                    stub_method("serialize", &[]),
                    stub_method("__serialize", &[]),
                    stub_method_typed("__unserialize", &[("data", "array")]),
                    stub_method("rewind", &[]),
                    stub_method("current", &[]),
                    stub_method("key", &[]),
                    stub_method("next", &[]),
                    stub_method("valid", &[]),
                    stub_method("seek", &["offset"]),
                    stub_method("__debugInfo", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // RecursiveArrayIterator — ArrayIterator + RecursiveIterator;
        // hasChildren/getChildren native-dispatch on ArrayIter too.
        reg(
            ClassDecl {
                name: "RecursiveArrayIterator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ArrayIterator".into()),
                implements: vec!["RecursiveIterator".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("hasChildren", &[]),
                    stub_method("getChildren", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // Generator — engine iterator produced by `yield` functions;
        // methods native-dispatch on the Generator internal.
        reg(
            ClassDecl {
                name: "Generator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: true,
                readonly: false,
                parent: None,
                implements: vec!["Iterator".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("rewind", &[]),
                    stub_method("valid", &[]),
                    stub_method("current", &[]),
                    stub_method("key", &[]),
                    stub_method("next", &[]),
                    stub_method("send", &["value"]),
                    stub_method("throw", &["exception"]),
                    stub_method("getReturn", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // SplFileInfo / DirectoryIterator — SPL filesystem surface;
        // methods native-dispatch on \0fi\0path / DirIter internals.
        reg(
            ClassDecl {
                name: "SplFileInfo".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("__construct", &["filename"]),
                    stub_method("getFilename", &[]),
                    stub_method("getBasename", &[]),
                    stub_method("getPathname", &[]),
                    stub_method("getPath", &[]),
                    stub_method("getExtension", &[]),
                    stub_method("getRealPath", &[]),
                    stub_method("isFile", &[]),
                    stub_method("isDir", &[]),
                    stub_method("isLink", &[]),
                    stub_method("isReadable", &[]),
                    stub_method("isWritable", &[]),
                    stub_method("isExecutable", &[]),
                    stub_method("getSize", &[]),
                    stub_method("getMTime", &[]),
                    stub_method("getType", &[]),
                    stub_method("__toString", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "DirectoryIterator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("SplFileInfo".into()),
                implements: vec!["Iterator".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("rewind", &[]),
                    stub_method("valid", &[]),
                    stub_method("current", &[]),
                    stub_method("key", &[]),
                    stub_method("next", &[]),
                    stub_method("isDot", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // FilesystemIterator / RecursiveDirectoryIterator — flagged dir
        // iteration + recursion (Composer's symfony/finder chain). Methods
        // native-dispatch through spl_method on the DirIter internal.
        let fsi_const = |n: &str, v: i64| crate::ast::ConstDecl {
            name: n.into(),
            value: Expr::Int(v),
            visibility: crate::ast::Visibility::Public,
            is_final: false,
            ty: None,
            attrs: vec![],
            decl_in: None,
            enum_case: false,
        };
        reg(
            ClassDecl {
                name: "FilesystemIterator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("DirectoryIterator".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("__construct", &["directory", "flags"]),
                    stub_method("rewind", &[]),
                    stub_method("valid", &[]),
                    stub_method("current", &[]),
                    stub_method("key", &[]),
                    stub_method("next", &[]),
                    stub_method("isDot", &[]),
                    stub_method("getFlags", &[]),
                    stub_method("setFlags", &["flags"]),
                ],
                props: vec![],
                consts: vec![
                    fsi_const("CURRENT_MODE_MASK", 240),
                    fsi_const("CURRENT_AS_PATHNAME", 32),
                    fsi_const("CURRENT_AS_FILEINFO", 0),
                    fsi_const("CURRENT_AS_SELF", 16),
                    fsi_const("KEY_MODE_MASK", 3840),
                    fsi_const("KEY_AS_PATHNAME", 0),
                    fsi_const("KEY_AS_FILENAME", 256),
                    fsi_const("NEW_CURRENT_AND_KEY", 256),
                    fsi_const("OTHER_MODE_MASK", 28672),
                    fsi_const("SKIP_DOTS", 4096),
                    fsi_const("UNIX_PATHS", 8192),
                    fsi_const("FOLLOW_SYMLINKS", 16384),
                ],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "RecursiveDirectoryIterator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("FilesystemIterator".into()),
                implements: vec!["RecursiveIterator".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("__construct", &["directory", "flags"]),
                    stub_method("hasChildren", &["allowLinks"]),
                    stub_method("getChildren", &[]),
                    stub_method("getSubPath", &[]),
                    stub_method("getSubPathname", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            iface(
                "ArrayAccess",
                &[],
                &["offsetExists", "offsetGet", "offsetSet", "offsetUnset"],
            ),
            true,
        );
        reg(
            iface("BackedEnum", &["UnitEnum"], &["from", "tryFrom"]),
            true,
        );
        reg(iface("UnitEnum", &[], &["cases"]), true);
        reg(iface("JsonSerializable", &[], &["jsonSerialize"]), true);
        // PDO + PDOStatement + PDOException — sqlite storage spike (#15).
        reg(
            ClassDecl {
                name: "PDO".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method_mix(
                        "__construct",
                        &["dsn"],
                        &["username", "password", "options"],
                    ),
                    stub_method("query", &["query"]),
                    stub_method("exec", &["statement"]),
                    stub_method_mix("prepare", &["query"], &["options"]),
                    stub_method_mix("lastInsertId", &[], &["name"]),
                    stub_method("beginTransaction", &[]),
                    stub_method("commit", &[]),
                    stub_method("rollBack", &[]),
                    stub_method("inTransaction", &[]),
                    stub_method_mix("quote", &["string"], &["type"]),
                    stub_method("setAttribute", &["attribute", "value"]),
                    stub_method("getAttribute", &["attribute"]),
                    stub_method("errorCode", &[]),
                    stub_method("errorInfo", &[]),
                ],
                props: vec![],
                consts: vec![
                    crate::ast::ConstDecl {
                        name: "FETCH_ASSOC".into(),
                        value: Expr::Int(2),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "FETCH_NUM".into(),
                        value: Expr::Int(3),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "FETCH_BOTH".into(),
                        value: Expr::Int(4),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "FETCH_OBJ".into(),
                        value: Expr::Int(5),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ATTR_ERRMODE".into(),
                        value: Expr::Int(3),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ATTR_DEFAULT_FETCH_MODE".into(),
                        value: Expr::Int(19),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ATTR_EMULATE_PREPARES".into(),
                        value: Expr::Int(20),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ERRMODE_SILENT".into(),
                        value: Expr::Int(0),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ERRMODE_WARNING".into(),
                        value: Expr::Int(1),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ERRMODE_EXCEPTION".into(),
                        value: Expr::Int(2),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "PARAM_STR".into(),
                        value: Expr::Int(2),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "PARAM_INT".into(),
                        value: Expr::Int(1),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "PARAM_BOOL".into(),
                        value: Expr::Int(5),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "PARAM_NULL".into(),
                        value: Expr::Int(0),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "PARAM_LOB".into(),
                        value: Expr::Int(3),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                ],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "PDOStatement".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method_mix("execute", &[], &["params"]),
                    stub_method_mix("fetch", &[], &["mode", "cursorOrientation", "cursorOffset"]),
                    stub_method_mix("fetchObject", &[], &["class", "constructorArgs"]),
                    stub_method_mix("fetchAll", &[], &["mode", "args"]),
                    stub_method_mix("fetchColumn", &[], &["column"]),
                    stub_method("rowCount", &[]),
                    stub_method("columnCount", &[]),
                    stub_method_mix("bindValue", &["param", "value"], &["type"]),
                    stub_method_mix(
                        "bindParam",
                        &["param", "var"],
                        &["type", "maxLength", "driverOptions"],
                    ),
                    stub_method("closeCursor", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            throwable_class("PDOException", Some("RuntimeException"), &[]),
            true,
        );
        // stdClass — the universal empty object.
        reg(
            ClassDecl {
                name: "stdClass".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // ArrayObject — SPL storage-backed object; methods are
        // native-dispatched through array_iter_method on the shared
        // ArrayIter internal (bug36214). Consts still cover
        // namespaces/ns_035, ns_036, bug42819.
        reg(
            ClassDecl {
                name: "ArrayObject".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![
                    "IteratorAggregate".into(),
                    "ArrayAccess".into(),
                    "Countable".into(),
                    "Serializable".into(),
                ],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method_mix("__construct", &[], &["array", "flags", "iteratorClass"]),
                    stub_method("append", &["value"]),
                    stub_method("asort", &["flags"]),
                    stub_method("count", &[]),
                    stub_method("exchangeArray", &["array"]),
                    stub_method("getArrayCopy", &[]),
                    stub_method("getFlags", &[]),
                    stub_method("getIterator", &[]),
                    stub_method("ksort", &["flags"]),
                    stub_method("natcasesort", &[]),
                    stub_method("natsort", &[]),
                    stub_method("offsetExists", &["key"]),
                    stub_method("offsetGet", &["key"]),
                    stub_method("offsetSet", &["key", "value"]),
                    stub_method("offsetUnset", &["key"]),
                    stub_method("setFlags", &["flags"]),
                    stub_method("uasort", &["callback"]),
                    stub_method("uksort", &["callback"]),
                    stub_method("serialize", &[]),
                    stub_method_typed("unserialize", &[("data", "string")]),
                    stub_method("__serialize", &[]),
                    stub_method_typed("__unserialize", &[("data", "array")]),
                    stub_method("__debugInfo", &[]),
                    stub_method("getIteratorClass", &[]),
                    stub_method("setIteratorClass", &["iteratorClass"]),
                ],
                props: vec![],
                consts: vec![
                    crate::ast::ConstDecl {
                        name: "STD_PROP_LIST".into(),
                        value: Expr::Int(1),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "ARRAY_AS_PROPS".into(),
                        value: Expr::Int(2),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                ],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // SplDoublyLinkedList / SplStack — container stubs with the
        // iteration-state internal the SPL method dispatch reads;
        // SplStack inherits everything from the DLL (closure_061,
        // bug70685).
        reg(
            ClassDecl {
                name: "SplDoublyLinkedList".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    stub_method("__construct", &[]),
                    stub_method("count", &[]),
                    stub_method("push", &["value"]),
                    stub_method("pop", &[]),
                    stub_method("top", &[]),
                    stub_method("bottom", &[]),
                    stub_method("isEmpty", &[]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "SplStack".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("SplDoublyLinkedList".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // DateTime — stub class whose ctor accepts an optional datetime
        // string; exists so `new DateTime(...)` type-checks
        // (compare_objects_basic2).
        reg(
            ClassDecl {
                name: "DateTime".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    Rc::new(MethodDecl {
                        decl: FunctionDecl {
                            ret: None,
                            name: "__construct".into(),
                            params: vec![Param {
                                name: "datetime".into(),
                                default: Some(Expr::Str("now".into())),
                                by_ref: false,
                                variadic: false,
                                ty: Some(vec!["string".into()]),
                                promoted: false,
                                vis: None,
                                readonly: false,
                                is_final: false,
                                set_vis: None,
                                hooks: None,
                            }],
                            body: vec![],
                            attrs: vec![],
                            by_ref: false,
                            line: 0,
                            end_line: 0,
                            file: String::new(),
                            ns: String::new(),
                            decl_in: None,
                        },
                        is_static: false,
                        is_abstract: false,
                        is_final: false,
                        visibility: Visibility::Public,
                        trait_alias_of: None,
                    }),
                    Rc::new(MethodDecl {
                        decl: FunctionDecl {
                            ret: Some(vec!["DateTime".into(), "false".into()]),
                            name: "createFromFormat".into(),
                            params: vec![
                                Param {
                                    name: "format".into(),
                                    default: None,
                                    by_ref: false,
                                    variadic: false,
                                    ty: Some(vec!["string".into()]),
                                    promoted: false,
                                    vis: None,
                                    readonly: false,
                                    is_final: false,
                                    set_vis: None,
                                    hooks: None,
                                },
                                Param {
                                    name: "datetime".into(),
                                    default: None,
                                    by_ref: false,
                                    variadic: false,
                                    ty: Some(vec!["string".into()]),
                                    promoted: false,
                                    vis: None,
                                    readonly: false,
                                    is_final: false,
                                    set_vis: None,
                                    hooks: None,
                                },
                                Param {
                                    name: "timezone".into(),
                                    default: Some(Expr::Null),
                                    by_ref: false,
                                    variadic: false,
                                    ty: Some(vec!["DateTimeZone".into(), "null".into()]),
                                    promoted: false,
                                    vis: None,
                                    readonly: false,
                                    is_final: false,
                                    set_vis: None,
                                    hooks: None,
                                },
                            ],
                            body: vec![],
                            attrs: vec![],
                            by_ref: false,
                            line: 0,
                            end_line: 0,
                            file: String::new(),
                            ns: String::new(),
                            decl_in: None,
                        },
                        is_static: true,
                        is_abstract: false,
                        is_final: false,
                        visibility: Visibility::Public,
                        trait_alias_of: None,
                    }),
                    Rc::new(MethodDecl {
                        decl: FunctionDecl {
                            ret: Some(vec!["int".into()]),
                            name: "getTimestamp".into(),
                            params: vec![],
                            body: vec![],
                            attrs: vec![],
                            by_ref: false,
                            line: 0,
                            end_line: 0,
                            file: String::new(),
                            ns: String::new(),
                            decl_in: None,
                        },
                        is_static: false,
                        is_abstract: false,
                        is_final: false,
                        visibility: Visibility::Public,
                        trait_alias_of: None,
                    }),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // DateTimeZone — stub with the const + tentative-typed
        // listIdentifiers the internal_parent variance tests override.
        reg(
            ClassDecl {
                name: "DateTimeZone".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![Rc::new(MethodDecl {
                    decl: FunctionDecl {
                        ret: Some(vec!["array".into()]),
                        name: "listIdentifiers".into(),
                        params: vec![
                            Param {
                                name: "timezoneGroup".into(),
                                default: Some(Expr::Const("DateTimeZone::ALL".into())),
                                by_ref: false,
                                variadic: false,
                                ty: Some(vec!["int".into()]),
                                promoted: false,
                                vis: None,
                                readonly: false,
                                is_final: false,
                                set_vis: None,
                                hooks: None,
                            },
                            Param {
                                name: "countryCode".into(),
                                default: Some(Expr::Null),
                                by_ref: false,
                                variadic: false,
                                ty: Some(vec!["string".into(), "null".into()]),
                                promoted: false,
                                vis: None,
                                readonly: false,
                                is_final: false,
                                set_vis: None,
                                hooks: None,
                            },
                        ],
                        body: vec![],
                        attrs: vec![],
                        by_ref: false,
                        line: 0,
                        end_line: 0,
                        file: String::new(),
                        ns: String::new(),
                        decl_in: None,
                    },
                    is_static: true,
                    is_abstract: false,
                    is_final: false,
                    visibility: Visibility::Public,
                    trait_alias_of: None,
                })],
                props: vec![],
                consts: vec![ConstDecl {
                    name: "ALL".into(),
                    value: Expr::Int(2047),
                    visibility: Visibility::Public,
                    is_final: false,
                    ty: None,
                    attrs: vec![],
                    decl_in: None,
                    enum_case: false,
                }],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // php_user_filter — the userland stream-filter base class
        // (user_filters.stub.php). Method bodies stay empty: calls into
        // the stubs are intercepted in method_invoke so zend's defaults
        // apply (filter() → PSFS_ERR_FATAL, onCreate() → true, …) and
        // userland overrides go through normal method dispatch.
        let uf_method = |name: &str, params: Vec<Param>, ret: Option<Vec<String>>| {
            Rc::new(MethodDecl {
                decl: FunctionDecl {
                    ret,
                    name: name.into(),
                    params,
                    body: vec![],
                    attrs: vec![],
                    by_ref: false,
                    line: 0,
                    end_line: 0,
                    file: String::new(),
                    ns: String::new(),
                    decl_in: None,
                },
                is_static: false,
                is_abstract: false,
                is_final: false,
                visibility: Visibility::Public,
                trait_alias_of: None,
            })
        };
        let uf_param = |name: &str, ty: Option<Vec<String>>, by_ref: bool| Param {
            name: name.into(),
            default: None,
            ty,
            by_ref,
            variadic: false,
            promoted: false,
            vis: None,
            readonly: false,
            is_final: false,
            set_vis: None,
            hooks: None,
        };
        reg(
            ClassDecl {
                name: "php_user_filter".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: {
                    let mut ms = vec![
                        uf_method(
                            "filter",
                            vec![
                                uf_param("in", None, false),
                                uf_param("out", None, false),
                                uf_param("consumed", None, true),
                                uf_param("closing", Some(vec!["bool".into()]), false),
                            ],
                            Some(vec!["int".into()]),
                        ),
                        uf_method("onCreate", vec![], Some(vec!["bool".into()])),
                        uf_method("onClose", vec![], Some(vec!["void".into()])),
                    ];
                    for m in [
                        "onFlush",
                        "onRead",
                        "onWrite",
                        "onAppend",
                        "onPrepend",
                        "onStart",
                        "onStop",
                        "onSeek",
                        "onSkip",
                        "onEof",
                        "onDetach",
                    ] {
                        ms.push(uf_method(m, vec![], Some(vec!["bool".into()])));
                    }
                    ms
                },
                props: vec![
                    PropDecl {
                        name: "filtername".into(),
                        default: Some(Expr::Str("".into())),
                        is_static: false,
                        visibility: Visibility::Public,
                        readonly: false,
                        ty: None,
                        is_abstract: false,
                        is_final: false,
                        set_vis: None,
                        decl_in: None,
                        hooks: None,
                        attrs: vec![],
                        line: 0,
                    },
                    PropDecl {
                        name: "params".into(),
                        default: Some(Expr::Str("".into())),
                        is_static: false,
                        visibility: Visibility::Public,
                        readonly: false,
                        ty: None,
                        is_abstract: false,
                        is_final: false,
                        set_vis: None,
                        decl_in: None,
                        hooks: None,
                        attrs: vec![],
                        line: 0,
                    },
                    PropDecl {
                        name: "stream".into(),
                        default: Some(Expr::Null),
                        is_static: false,
                        visibility: Visibility::Public,
                        readonly: false,
                        ty: None,
                        is_abstract: false,
                        is_final: false,
                        set_vis: None,
                        decl_in: None,
                        hooks: None,
                        attrs: vec![],
                        line: 0,
                    },
                ],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // StreamBucket — the object stream_bucket_make_writeable() /
        // stream_bucket_new() hand to php_user_filter::filter().
        reg(
            ClassDecl {
                name: "StreamBucket".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![],
                props: {
                    let p = |name: &str, default: Option<Expr>, ty: Option<Vec<String>>| PropDecl {
                        name: name.into(),
                        default,
                        is_static: false,
                        visibility: Visibility::Public,
                        readonly: false,
                        ty,
                        is_abstract: false,
                        is_final: false,
                        set_vis: None,
                        decl_in: None,
                        hooks: None,
                        attrs: vec![],
                        line: 0,
                    };
                    vec![
                        p("bucket", Some(Expr::Null), None),
                        p("data", None, Some(vec!["string".into()])),
                        p("datalen", None, Some(vec!["int".into()])),
                        p("dataLength", None, Some(vec!["int".into()])),
                    ]
                },
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // Reflection stubs — enough surface for the hooked-prop tests:
        // ReflectionClass::newInstanceWithoutConstructor builds the shell
        // without running __construct; ReflectionProperty::isInitialized
        // checks slot presence (typed props with no default start uninit).
        let mk_method = |name: &str, params: Vec<Param>| {
            Rc::new(MethodDecl {
                decl: FunctionDecl {
                    ret: None,
                    name: name.into(),
                    params,
                    body: vec![],
                    attrs: vec![],
                    by_ref: false,
                    line: 0,
                    end_line: 0,
                    file: String::new(),
                    ns: String::new(),
                    decl_in: None,
                },
                is_static: false,
                is_abstract: false,
                is_final: false,
                visibility: Visibility::Public,
                trait_alias_of: None,
            })
        };
        let str_param = |n: &str| Param {
            name: n.into(),
            default: None,
            by_ref: false,
            variadic: false,
            ty: Some(vec!["string".into()]),
            promoted: false,
            vis: None,
            readonly: false,
            is_final: false,
            set_vis: None,
            hooks: None,
        };
        let any_param = |n: &str, variadic: bool| Param {
            name: n.into(),
            default: None,
            by_ref: false,
            variadic,
            ty: None,
            promoted: false,
            vis: None,
            readonly: false,
            is_final: false,
            set_vis: None,
            hooks: None,
        };
        let mk_smethod = |name: &str, params: Vec<Param>| {
            let mut m = (*mk_method(name, params)).clone();
            m.is_static = true;
            Rc::new(m)
        };
        reg(
            ClassDecl {
                name: "ReflectionClass".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![any_param("class", false)]),
                    mk_method("newInstanceWithoutConstructor", vec![]),
                    mk_method("newInstance", vec![any_param("args", true)]),
                    mk_method("newInstanceArgs", vec![any_param("args", false)]),
                    mk_method("getName", vec![]),
                    mk_method("getAttributes", vec![]),
                    mk_method("getConstant", vec![str_param("name")]),
                    mk_method("getConstants", vec![]),
                    mk_method("getReflectionConstant", vec![str_param("name")]),
                    mk_method("getReflectionConstants", vec![]),
                    mk_method("getTraitAliases", vec![]),
                    mk_method("getProperty", vec![str_param("name")]),
                    mk_method("hasProperty", vec![str_param("name")]),
                    mk_method("getDefaultProperties", vec![]),
                    mk_method("getInterfaceNames", vec![]),
                    mk_method("getInterfaces", vec![]),
                    mk_method("getParentClass", vec![]),
                    mk_method("getShortName", vec![]),
                    mk_method("getNamespaceName", vec![]),
                    mk_method("getFileName", vec![]),
                    mk_method("isInternal", vec![]),
                    mk_method("isUserDefined", vec![]),
                    mk_method("isAbstract", vec![]),
                    mk_method("isFinal", vec![]),
                    mk_method("isInterface", vec![]),
                    mk_method("isTrait", vec![]),
                    mk_method("isEnum", vec![]),
                    mk_method("isAnonymous", vec![]),
                    mk_method("isInstantiable", vec![]),
                    mk_method("isCloneable", vec![]),
                    mk_method("isReadOnly", vec![]),
                    mk_method("isIterable", vec![]),
                    mk_method("isSubclassOf", vec![any_param("class", false)]),
                    mk_method("implementsInterface", vec![any_param("interface", false)]),
                    mk_method("getMethods", vec![any_param("filter", false)]),
                    mk_method("getMethod", vec![str_param("name")]),
                    mk_method("hasMethod", vec![str_param("name")]),
                    mk_method("getDocComment", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "ReflectionFunction".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionFunctionAbstract".into()),
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![any_param("function", false)]),
                    mk_method("invoke", vec![any_param("args", true)]),
                    mk_method("invokeArgs", vec![any_param("args", false)]),
                    mk_method("getName", vec![]),
                    mk_method("getAttributes", vec![]),
                    mk_method("getParameters", vec![]),
                    mk_method("isClosure", vec![]),
                    mk_method("isAnonymous", vec![]),
                    mk_method("getClosure", vec![]),
                    mk_method("getClosureScopeClass", vec![]),
                    mk_method("getClosureCalledClass", vec![]),
                    mk_method("getClosureThis", vec![]),
                    mk_method("getShortName", vec![]),
                    mk_method("getNamespaceName", vec![]),
                    mk_method("inNamespace", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "ReflectionMethod".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionFunctionAbstract".into()),
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method(
                        "__construct",
                        vec![any_param("class", false), any_param("name", false)],
                    ),
                    mk_method(
                        "invoke",
                        vec![any_param("object", false), any_param("args", true)],
                    ),
                    mk_method(
                        "invokeArgs",
                        vec![any_param("object", false), any_param("args", false)],
                    ),
                    mk_method("getName", vec![]),
                    mk_method("getShortName", vec![]),
                    mk_method("getNamespaceName", vec![]),
                    mk_method("inNamespace", vec![]),
                    mk_method("isFinal", vec![]),
                    mk_method("isAbstract", vec![]),
                    mk_method("isStatic", vec![]),
                    mk_method("isPublic", vec![]),
                    mk_method("isProtected", vec![]),
                    mk_method("isPrivate", vec![]),
                    mk_method("getParameters", vec![]),
                    mk_method("getClosure", vec![any_param("object", false)]),
                    mk_method("getClosureScopeClass", vec![]),
                    mk_method("getClosureCalledClass", vec![]),
                    mk_method("getClosureThis", vec![]),
                    mk_method("getDeclaringClass", vec![]),
                    mk_method("getFileName", vec![]),
                    mk_method("isConstructor", vec![]),
                    mk_method("isDestructor", vec![]),
                    mk_method("getAttributes", vec![]),
                    mk_method("getDocComment", vec![]),
                    mk_method("getStartLine", vec![]),
                    mk_method("getEndLine", vec![]),
                    mk_method("getDeclaringNamespace", vec![]),
                    mk_method("hasReturnType", vec![]),
                    mk_method("getReturnType", vec![]),
                    mk_method("isDeprecated", vec![]),
                ],
                props: vec![],
                consts: [
                    ("IS_STATIC", 16),
                    ("IS_PUBLIC", 1),
                    ("IS_PROTECTED", 2),
                    ("IS_PRIVATE", 4),
                    ("IS_ABSTRACT", 64),
                    ("IS_FINAL", 32),
                ]
                .iter()
                .map(|(n, v)| crate::ast::ConstDecl {
                    name: (*n).into(),
                    value: Expr::Int(*v),
                    visibility: crate::ast::Visibility::Public,
                    is_final: false,
                    ty: None,
                    attrs: vec![],
                    decl_in: None,
                    enum_case: false,
                })
                .collect(),
                file: String::new(),
                line: 0,
            },
            false,
        );
        // ReflectionParameter — produced by getParameters();
        // per-param data lives under \0rp\0* props.
        reg(
            ClassDecl {
                name: "ReflectionParameter".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("isCallable", vec![]),
                    mk_method("isVariadic", vec![]),
                    mk_method("hasType", vec![]),
                    mk_method("getType", vec![]),
                    mk_method("getName", vec![]),
                    mk_method("getClass", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // ReflectionClassConstant — produced by ReflectionClass::
        // getReflectionConstant(s) (constant_019-021).
        reg(
            ClassDecl {
                name: "ReflectionClassConstant".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method(
                        "__construct",
                        vec![any_param("class", false), any_param("name", false)],
                    ),
                    mk_method("getName", vec![]),
                    mk_method("getValue", vec![]),
                    mk_method("getDocComment", vec![]),
                    mk_method("getAttributes", vec![]),
                    mk_method("getDeclaringClass", vec![]),
                    mk_method("isPublic", vec![]),
                    mk_method("isProtected", vec![]),
                    mk_method("isPrivate", vec![]),
                    mk_method("isFinal", vec![]),
                    mk_method("isEnumCase", vec![]),
                    mk_method("isDeprecated", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // ReflectionAttribute — produced by getAttributes(); carries the
        // attribute name + unevaluated arg exprs + target kind.
        reg(
            ClassDecl {
                name: "ReflectionAttribute".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("getName", vec![]),
                    mk_method("getArguments", vec![]),
                    mk_method("newInstance", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // Attribute — the `#[Attribute]` marker class + TARGET_* flags.
        reg(
            ClassDecl {
                name: "Attribute".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![],
                props: vec![],
                consts: vec![
                    crate::ast::ConstDecl {
                        name: "TARGET_CLASS".into(),
                        value: Expr::Int(1),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "TARGET_FUNCTION".into(),
                        value: Expr::Int(2),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "TARGET_METHOD".into(),
                        value: Expr::Int(4),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "TARGET_PROPERTY".into(),
                        value: Expr::Int(8),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "TARGET_CLASS_CONSTANT".into(),
                        value: Expr::Int(16),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "TARGET_PARAMETER".into(),
                        value: Expr::Int(32),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "TARGET_ALL".into(),
                        value: Expr::Int(63),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                    crate::ast::ConstDecl {
                        name: "IS_REPEATABLE".into(),
                        value: Expr::Int(64),
                        visibility: crate::ast::Visibility::Public,
                        is_final: false,
                        ty: None,
                        attrs: vec![],
                        decl_in: None,
                        enum_case: false,
                    },
                ],
                file: String::new(),
                line: 0,
            },
            false,
        );
        reg(
            ClassDecl {
                name: "ReflectionProperty".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method(
                        "__construct",
                        vec![str_param("class"), str_param("property")],
                    ),
                    mk_method(
                        "isInitialized",
                        vec![Param {
                            name: "object".into(),
                            default: Some(Expr::Null),
                            by_ref: false,
                            variadic: false,
                            ty: None,
                            promoted: false,
                            vis: None,
                            readonly: false,
                            is_final: false,
                            set_vis: None,
                            hooks: None,
                        }],
                    ),
                    mk_method("getName", vec![]),
                    mk_method("getType", vec![]),
                    mk_method("getValue", vec![str_param("object")]),
                    mk_method("setValue", vec![str_param("object"), str_param("value")]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // ReflectionObject — minimal stub (bug50146).
        reg(
            ClassDecl {
                name: "ReflectionObject".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![str_param("object")]),
                    mk_method("hasProperty", vec![str_param("name")]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // ReflectionNamedType — produced by getType() on a property /
        // parameter / return (typed_properties_018).
        reg(
            ClassDecl {
                name: "ReflectionNamedType".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionType".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("getName", vec![]),
                    mk_method("allowsNull", vec![]),
                    mk_method("isBuiltin", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // Remaining Reflection hierarchy — PHPUnit's bootstrap
        // reflects over test classes and statics heavily.
        for d in [
            ClassDecl {
                name: "ReflectionFunctionAbstract".into(),
                kind: ClassKind::Class,
                is_abstract: true,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("getName", vec![]),
                    mk_method("getParameters", vec![]),
                    mk_method("getAttributes", vec![]),
                    mk_method("getDocComment", vec![]),
                    mk_method("getReturnType", vec![]),
                    mk_method("getNamespaceName", vec![]),
                    mk_method("getShortName", vec![]),
                    mk_method("getNumberOfParameters", vec![]),
                    mk_method("getNumberOfRequiredParameters", vec![]),
                    mk_method("isStatic", vec![]),
                    mk_method("isClosure", vec![]),
                    mk_method("returnsReference", vec![]),
                    mk_method("hasReturnType", vec![]),
                    mk_method("getStaticVariables", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionObject".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionClass".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![mk_method("__construct", vec![any_param("object", false)])],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionEnum".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionClass".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![any_param("class", false)]),
                    mk_method("getCases", vec![]),
                    mk_method("getCase", vec![str_param("name")]),
                    mk_method("hasCase", vec![str_param("name")]),
                    mk_method("getBackingType", vec![]),
                    mk_method("isBacked", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionEnumUnitCase".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionClassConstant".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![mk_method("getEnum", vec![]), mk_method("getValue", vec![])],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionEnumBackedCase".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionEnumUnitCase".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![mk_method("getBackingValue", vec![])],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionType".into(),
                kind: ClassKind::Class,
                is_abstract: true,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Stringable".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![mk_method("allowsNull", vec![])],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionUnionType".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionType".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("getTypes", vec![]),
                    mk_method("allowsNull", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionIntersectionType".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionType".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("getTypes", vec![]),
                    mk_method("allowsNull", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionExtension".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![str_param("name")]),
                    mk_method("getName", vec![]),
                    mk_method("getVersion", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionZendExtension".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: Some("ReflectionExtension".into()),
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![str_param("name")]),
                    mk_method("getName", vec![]),
                    mk_method("getVersion", vec![]),
                    mk_method("getAuthor", vec![]),
                    mk_method("getCopyright", vec![]),
                    mk_method("getURL", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionGenerator".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![any_param("generator", false)]),
                    mk_method("getFunction", vec![]),
                    mk_method("getThis", vec![]),
                    mk_method("getExecutingFile", vec![]),
                    mk_method("getExecutingLine", vec![]),
                    mk_method("getTrace", vec![]),
                    mk_method("getExecutingGenerator", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionReference".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_smethod(
                        "fromArrayElement",
                        vec![any_param("array", false), any_param("key", false)],
                    ),
                    mk_method("getId", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            ClassDecl {
                name: "ReflectionConstant".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: false,
                readonly: false,
                parent: None,
                implements: vec!["Reflector".into()],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![
                    mk_method("__construct", vec![str_param("name")]),
                    mk_method("getName", vec![]),
                    mk_method("getValue", vec![]),
                    mk_method("getNamespaceName", vec![]),
                    mk_method("getShortName", vec![]),
                    mk_method("isDeprecated", vec![]),
                ],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
        ] {
            reg(d, false);
        }
        reg(
            throwable_class("Exception", None, &["message", "code", "file", "line"]),
            false,
        );
        reg(
            throwable_class("Error", None, &["message", "code", "file", "line"]),
            false,
        );
        // Closure — name must resolve for `\Closure::bind()` /
        // `\Closure::fromCallable()` (composer's ClassLoader uses bind to
        // scope-isolate `include`). Methods dispatch natively in
        // static_invoke / the Value::Callable method arm.
        reg(
            ClassDecl {
                name: "Closure".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: true,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: vec![],
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        // WeakReference — native dispatch: static_invoke's `create`
        // and method_invoke's `get` on the WeakRef internal.
        let weakref_methods = vec![
            Rc::new(MethodDecl {
                decl: FunctionDecl {
                    ret: Some(vec!["WeakReference".into()]),
                    name: "create".into(),
                    params: vec![Param {
                        name: "object".into(),
                        default: None,
                        by_ref: false,
                        variadic: false,
                        ty: Some(vec!["object".into()]),
                        promoted: false,
                        vis: None,
                        readonly: false,
                        is_final: false,
                        set_vis: None,
                        hooks: None,
                    }],
                    body: vec![],
                    attrs: vec![],
                    by_ref: false,
                    line: 0,
                    end_line: 0,
                    file: String::new(),
                    ns: String::new(),
                    decl_in: None,
                },
                is_static: true,
                is_abstract: false,
                is_final: false,
                visibility: Visibility::Public,
                trait_alias_of: None,
            }),
            Rc::new(MethodDecl {
                decl: FunctionDecl {
                    ret: Some(vec!["object".into(), "null".into()]),
                    name: "get".into(),
                    params: vec![],
                    body: vec![],
                    attrs: vec![],
                    by_ref: false,
                    line: 0,
                    end_line: 0,
                    file: String::new(),
                    ns: String::new(),
                    decl_in: None,
                },
                is_static: false,
                is_abstract: false,
                is_final: false,
                visibility: Visibility::Public,
                trait_alias_of: None,
            }),
        ];
        reg(
            ClassDecl {
                name: "WeakReference".into(),
                kind: ClassKind::Class,
                is_abstract: false,
                is_final: true,
                readonly: false,
                parent: None,
                implements: vec![],
                attrs: vec![],
                traits: vec![],
                adaptations: vec![],
                methods: weakref_methods,
                props: vec![],
                consts: vec![],
                file: String::new(),
                line: 0,
            },
            false,
        );
        {
            // ErrorException declares its own 6-arg __construct shape
            // (severity/filename/line before previous), a `severity`
            // prop and getSeverity() — the ctor stub reads the class
            // family to pick the signature.
            let mut d = throwable_class(
                "ErrorException",
                Some("Exception"),
                &["message", "code", "file", "line", "severity"],
            );
            d.methods.push(method("getSeverity", &[]));
            reg(d, false);
        }
        for (name, parent) in [
            ("RuntimeException", "Exception"),
            ("LogicException", "Exception"),
            ("InvalidArgumentException", "LogicException"),
            ("LengthException", "LogicException"),
            ("OutOfRangeException", "LogicException"),
            ("UnexpectedValueException", "RuntimeException"),
            ("BadFunctionCallException", "LogicException"),
            ("BadMethodCallException", "BadFunctionCallException"),
            ("OutOfBoundsException", "RuntimeException"),
            ("DomainException", "LogicException"),
            ("RangeException", "RuntimeException"),
            ("UnderflowException", "RuntimeException"),
            ("OverflowException", "RuntimeException"),
            ("ValueError", "Error"),
            ("TypeError", "Error"),
            ("ArgumentCountError", "TypeError"),
            ("ArithmeticError", "Error"),
            ("DivisionByZeroError", "ArithmeticError"),
            ("CompileError", "Error"),
            ("ParseError", "CompileError"),
            ("AssertionError", "Error"),
            ("UnhandledMatchError", "Error"),
            ("ReflectionException", "Exception"),
        ] {
            reg(
                throwable_class(name, Some(parent), &["message", "code", "file", "line"]),
                false,
            );
        }
    }
}
